services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped
  database:
    image: "postgres:16.0-alpine"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
